// <auto-generated />
using System;
using CobranzaAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CobranzaAPI.Migrations
{
    [DbContext(typeof(CobranzaContext))]
    partial class CobranzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("CobranzaApi.Core.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Activo");

                    b.Property<string>("DireccionCliente")
                        .HasMaxLength(300);

                    b.Property<DateTime>("FecRegistro");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("TelefonoCliente")
                        .HasMaxLength(100);

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
